[package]
name = "metrics-exporter-csv"
version = "0.1.1"
authors = [
  "ApertureC Team <aperturec@zetier.com>",
  "Joe Kale <joe@zetier.com>"
]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/Zetier/metrics-exporter-csv"
description = "A metrics recorder that writes metric snapshots to CSV files"
license = "MIT OR Apache-2.0"
keywords = ["metrics", "csv", "exporter", "recorder", "snapshot"]
categories = ["development-tools::debugging"]

[dependencies]
chrono = "0.4"
csv-async = "1.3.1"
event-listener = "5.4"
itertools = "0.12"
metrics = "0.24"
metrics-util = "0.20"
smol = "2.0.2"
thiserror = "2.0"
tracing = "0.1"
tokio = { version = "1", features = ["rt"], optional = true }

[dev-dependencies]
tempfile = "3"

[features]
tokio = ["dep:tokio"]

[workspace]
members = [
    ".",
    "tools/long2wide",
]
resolver = "2"
